name: Haskell CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: haskell/actions/setup@v1
      with:
        ghc-version: '8.10.7'
        stack-version: 'latest'

    - name: Cache ~/.stack
      id: cache-stack
      uses: actions/cache@v1
      env:
        cache-name: cache-stack
      with:
        path: ~/.stack
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.yaml') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
    
    - name: Cache .stack-work
      id: cache-stack-work
      uses: actions/cache@v1
      env:
        cache-name: cache-stack-work
      with:
        path: .stack-work
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-${{ github.sha }}
          ${{ runner.os }}-build-${{ env.cache-name }}-

    - name: Build
      run: stack build
    - name: Run tests
      run: stack test
